name: SonarCloud Maven Analysis



on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: self-hosted

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'

      - name: Analyze Sonar
        run: |
          mvn sonar:sonar -Dsonar.projectKey=alissonit_fiap-pedidos -Dsonar.organization=alissonit -Dsonar.host.url=https://sonarcloud.io -Dsonar.token=${{ secrets.SONAR_TOKEN }}
