name: SonarCloud Maven Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 17

      - name: Build and Analyze
        run: |
          mvn clean install
          mvn sonar:sonar -Dsonar.projectKey=alissonit -Dsonar.organization=alissonit_fiap-pedidos -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=${{ secrets.SONAR_TOKEN }}
